; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 9600
monitor_filters = direct
lib_deps = robtillaart/ANSI@^0.3.2
; Leave these 3 lines commented out until you use ESP-PROG, note check if COM3 or change
;monitor_port = COM3
debug_init_break = tbreak setup
upload_protocol = esptool
debug_tool = custom

debug_server =
    ${platformio.packages_dir}/tool-openocd-esp32/bin/openocd
    -s ${platformio.packages_dir}/tool-openocd-esp32/share/openocd/scripts
    -f board/esp32-bridge.cfg
    -c "adapter speed 5000"

build_type = debug